// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPqCgdomXYrg4rpP2o0vwAyNejHiqak58',
    appId: '1:1024240629640:web:e7c6932c618afa4db56c3d',
    messagingSenderId: '1024240629640',
    projectId: 'api-recipe-d2a38',
    authDomain: 'api-recipe-d2a38.firebaseapp.com',
    storageBucket: 'api-recipe-d2a38.appspot.com',
    measurementId: 'G-TEETG8Y0C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB59WFZnk8_Jea-sS0iySsgTrfxrLyBAa4',
    appId: '1:1024240629640:android:e9d876967a265bc0b56c3d',
    messagingSenderId: '1024240629640',
    projectId: 'api-recipe-d2a38',
    storageBucket: 'api-recipe-d2a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDld3jR_UnjW30BYWPkAAqAdMA0FqlRlWs',
    appId: '1:1024240629640:ios:c01b752425b49680b56c3d',
    messagingSenderId: '1024240629640',
    projectId: 'api-recipe-d2a38',
    storageBucket: 'api-recipe-d2a38.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDld3jR_UnjW30BYWPkAAqAdMA0FqlRlWs',
    appId: '1:1024240629640:ios:c0a6693ba34085e3b56c3d',
    messagingSenderId: '1024240629640',
    projectId: 'api-recipe-d2a38',
    storageBucket: 'api-recipe-d2a38.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
